import React, { JSX } from "react";
import {
  SiTypescript,
  SiJavascript,
  SiNodemon,
  SiNodedotjs,
  SiMongodb,
  SiNextdotjs,
  SiReact,
  SiTailwindcss,
  SiEslint,
  SiRedis,
  SiJsonwebtokens,
  SiMaildotru,
  SiOpenjdk,
  SiReactrouter,
  SiFramer,
  SiGithub,
  SiVite,
  SiFirebase,
  SiPostgresql,
  SiPrisma,
  SiBun,
  SiGooglegemini,
  SiHono,
  SiMariadb,
  SiCloudinary,
  SiWhatsapp,
  SiReactquery,
  SiRadixui,
  SiLeaflet,
  SiTauri,
  SiRust,
  SiShadcnui,
  SiSocketdotio,
} from "react-icons/si";
import { TbChartAreaLine, TbLayoutDashboard } from "react-icons/tb";
import { MdAnimation, MdSmartToy } from "react-icons/md";
export const stackIcons: Record<string, JSX.Element> = {
  typescript: <SiTypescript className="text-blue-500" />,
  javascript: <SiJavascript className="text-yellow-500" />,
  nodemon: <SiNodemon className="text-green-500" />,
  nodejs: <SiNodedotjs className="text-green-600" />,
  mongodb: <SiMongodb className="text-green-700" />,
  nextjs: <SiNextdotjs className="text-white" />,
  react: <SiReact className="text-blue-400" />,
  swr: <SiReact className="text-cyan-500" />,
  tailwindcss: <SiTailwindcss className="text-teal-400" />,
  eslint: <SiEslint className="text-purple-500" />,
  redis: <SiRedis className="text-red-500" />,
  jwt: <SiJsonwebtokens className="text-orange-500" />,
  mongoose: <SiMongodb className="text-green-700" />,
  nodemailer: <SiMaildotru className="text-red-500" />,
  java: <SiOpenjdk className="text-red-500" />,
  "react-router": <SiReactrouter className="text-red-600" />,
  "framer-motion": <SiFramer className="text-pink-500" />,
  "gh-pages": <SiGithub className="text-gray-700" />,
  vite: <SiVite className="text-purple-500" />,
  firebase: <SiFirebase className="text-orange-500" />,
  postgresql: <SiPostgresql className="text-blue-400" />,
  prisma: <SiPrisma className="text-white" />,
  bun: <SiBun className="text-pink-300" />,
  gemini: <SiGooglegemini className="text-blue-500" />,
  hono: <SiHono className="text-orange-500" />,
  mariadb: <SiMariadb className="text-white" />,
  cloudinary: <SiCloudinary className="text-blue-500" />,
  "whatsapp-bot": <SiWhatsapp className="text-green-500" />,
  "react-query": <SiReactquery className="text-red-500" />,
  "radix-ui": <SiRadixui className="text-white" />,
  recharts: <TbChartAreaLine className="text-blue-400" />,
  leaflet: <SiLeaflet className="text-green-500" />,
  lottie: <MdAnimation className="text-teal-400" />,
  baileys: <MdSmartToy className="text-gray-300" />,
  tauri: <SiTauri className="text-yellow-500" />,
  rust: <SiRust className="text-orange-500" />,
  shadcn: <SiShadcnui className="text-white" />,
  "socket-io": <SiSocketdotio className="text-white" />,
  flowbite: <TbLayoutDashboard className="text-blue-500" />,
};
